"""media table columns

Revision ID: 138cb2eb1ec9
Revises: 5642e8c516b2
Create Date: 2022-03-07 08:19:01.777223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '138cb2eb1ec9'
down_revision = '5642e8c516b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('ipfs_hash', sa.String(), nullable=True))
    op.add_column('media', sa.Column('pin_size', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('name', sa.String(), nullable=True))
    op.add_column('media', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('media', 'pinSize')
    op.drop_column('media', 'ipfsHash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('ipfsHash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('pinSize', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('media', 'description')
    op.drop_column('media', 'name')
    op.drop_column('media', 'pin_size')
    op.drop_column('media', 'ipfs_hash')
    # ### end Alembic commands ###
