"""media table updates

Revision ID: 2653f1f42d06
Revises: c7c9ee56a434
Create Date: 2022-03-16 16:29:01.071828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2653f1f42d06'
down_revision = 'c7c9ee56a434'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('media_ipfs_hash', sa.String(), nullable=True))
    op.add_column('media', sa.Column('ipfs_image_url', sa.String(), nullable=True))
    op.drop_column('media', 'pin_size')
    # ### end Alembic commands ###

    op.alter_column('media', 'key', nullable=True, new_column_name='s3_key')
    op.alter_column('media', 'ipfs_hash', nullable=True, new_column_name='json_ipfs_hash')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('pin_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('media', 'ipfs_image_url')
    op.drop_column('media', 'media_ipfs_hash')
    # ### end Alembic commands ###

    op.alter_column('media', 's3_key', nullable=True, new_column_name='key')
    op.alter_column('media', 'json_ipfs_hash', nullable=True, new_column_name='ipfs_hash')

