"""user_id_relationship

Revision ID: a7ac0bcc003f
Revises: a4801255f707
Create Date: 2022-03-10 10:18:16.367472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7ac0bcc003f'
down_revision = 'a4801255f707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('user_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_foreign_key(None, 'media', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_column('media', 'user_id')
    # ### end Alembic commands ###
