"""media is mined column

Revision ID: b1f2a973e47e
Revises: e7c7ef09ba49
Create Date: 2022-03-18 16:44:02.938584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1f2a973e47e'
down_revision = 'e7c7ef09ba49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'is_confirmed')
    # ### end Alembic commands ###
