"""twitter_handle

Revision ID: b4a627ff1080
Revises: de6e1cf02056
Create Date: 2022-03-30 08:45:38.315938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a627ff1080'
down_revision = 'de6e1cf02056'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twitter_handle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'twitter_handle')
    # ### end Alembic commands ###
