"""media txn hash

Revision ID: c7c9ee56a434
Revises: cef2a6db101f
Create Date: 2022-03-16 08:53:23.692910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7c9ee56a434'
down_revision = 'cef2a6db101f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('txn_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'txn_hash')
    # ### end Alembic commands ###
