"""payment_intent col

Revision ID: ce5be026aad5
Revises: b1f2a973e47e
Create Date: 2022-03-18 17:26:26.282617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce5be026aad5'
down_revision = 'b1f2a973e47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('intent_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('intent_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'intent_confirmed')
    op.drop_column('payments', 'intent_id')
    # ### end Alembic commands ###
