"""add payment fields

Revision ID: cef2a6db101f
Revises: ca198a41da23
Create Date: 2022-03-14 19:25:15.534557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef2a6db101f'
down_revision = 'ca198a41da23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('stripe_id', sa.String(), nullable=True))
    op.add_column('payments', sa.Column('amount_cents', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'amount_cents')
    op.drop_column('payments', 'stripe_id')
    # ### end Alembic commands ###
