"""remove-username

Revision ID: ecc97b25b804
Revises: b4a627ff1080
Create Date: 2022-04-06 09:25:26.229404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ecc97b25b804'
down_revision = 'b4a627ff1080'
branch_labels = None
depends_on = None

# Manually edited to leave in specific tables/columns

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
